name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: image-collage
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: image-collage.exe
            archive: zip
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: image-collage
            archive: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: image-collage
            archive: tar.gz
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Package (tar.gz)
        if: matrix.archive == 'tar.gz'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../image-collage-${{ github.ref_name }}-${{ matrix.target }}.tar.gz ${{ matrix.binary }}
      
      - name: Package (zip)
        if: matrix.archive == 'zip'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../image-collage-${{ github.ref_name }}-${{ matrix.target }}.zip ${{ matrix.binary }}
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./image-collage-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}
          asset_name: image-collage-${{ github.ref_name }}-${{ matrix.target }}.${{ matrix.archive }}
          asset_content_type: application/octet-stream